openapi: 3.1.0
info:
  title: My Example API
  version: 1.0.0

tags:
  - name: Auth
    description: Authentication endpoints

paths:
  /auth/login-inline:
    $ref: './paths/login-inline.yaml'
  /auth/login-md:
    $ref: './paths/login-inline.yaml'